export const events = [
  {
    title: "GitHub Universe 2026",
    image: "/images/event1.png",
    slug: "github-universe-2026",
    location: "Fort Mason Center, San Francisco, CA",
    date: "October 28–29, 2026",
    time: "9:00 AM",
  },
  {
    title: "CityJS Athens 2026",
    image: "/images/event2.png",
    slug: "cityjs-athens-2026",
    location: "Athens, Greece",
    date: "October 21–23, 2026",
    time: "9:00 AM",
  },
  {
    title: "Build, Ship, Shape: Amazon Developer Hackathon",
    image: "/images/event3.png",
    slug: "amazon-build-ship-shape-hackathon",
    location: "Online",
    date: "Submission deadline: October 23, 2026",
    time: "11:59 PM PDT",
  },
  {
    title: "OpenCV AI Competition 2026",
    image: "/images/event4.png",
    slug: "opencv-ai-competition-2026",
    location: "Online",
    date: "Submission deadline: October 27, 2026",
    time: "11:59 PM PDT",
  },
  {
    title: "GitHub Universe on the Road: Bengaluru",
    image: "/images/event5.png",
    slug: "github-universe-on-the-road-bengaluru",
    location: "Conrad Bengaluru, India",
    date: "December 1, 2026",
    time: "9:00 AM",
  },
  {
    title: "React Conf Japan 2027",
    image: "/images/event6.png",
    slug: "react-conf-japan-2027",
    location: "Tokyo, Japan",
    date: "April 24, 2027",
    time: "9:00 AM",
  },
];
